### PR TITLE
Modified effect.py to add new vep splice region annotations, accordin…

### PR DESCRIPTION
**Pull request by oleraj**
…g to https://useast.ensembl.org/info/genome/variation/prediction/predicted_data.html

As of vep105, three new annotations were added, i.e., 

https://useast.ensembl.org/info/docs/tools/vep/script/vep_download.html#history

> 3 new Sequence Ontology terms are reported for more detailed splice consequence annotation
> splice_donor_5th_base_variant ([SO:0001787](http://www.sequenceontology.org/miso/current_release/term/SO:0001787))
> splice_donor_region_variant ([SO:0002170](http://www.sequenceontology.org/miso/current_release/term/SO:0002170))
> splice_polypyrimidine_tract_variant ([SO:0002169](http://www.sequenceontology.org/miso/current_release/term/SO:0002169))

I tested these changes locally using a VCF annotated by vep108 and it works for me in vcfanno + vcf2db.

See also related issue here: https://github.com/arq5x/gemini/issues/926

Let me know if any questions.

Thanks, 
Andrew

### CODE REVIEW

**Comment by brentp** [comment]
thanks Andrew!

**Comment by Luciagenetic** [comment]
Hi, how do I insert these annotations  splice_donor_5th_base_variant ([SO:0001787](http://www.sequenceontology.org/miso/current_release/term/SO:0001787))
splice_donor_region_variant ([SO:0002170](http://www.sequenceontology.org/miso/current_release/term/SO:0002170))
splice_polypyrimidine_tract_variant ([SO:0002169](http://www.sequenceontology.org/miso/current_release/term/SO:0002169)) with gemini? After annotating my vcf with vep and subsequently creating the db with gemini it gives me these warnings:
WARNING: unknown severity for 'splice_polypyrimidine_tract_variant&intron_variant&non_coding_transcript_variant|||9892|SNAP91|NR_164846.1|||||misc_RNA|NR_164846.1:n.591-9del||||' with effect 'splice_polypyrimidine_tract_variant'
thanks
Lucia

**Comment by oleraj** [comment]
Hi @Luciagenetic, if your gemini was compiled with this latest version of geneimpacts, it should handle these annotations fine.  Not sure if it will work, but you could try downloading this repo and exporting the path to PYTHONPATH, e.g., 
```
export PYTHONPATH=/path/to/geneimpacts:$PYTHONPATH
```
Then try running gemini load again.  If it doesn't work, and your gemini is using an older version of geneimpacts, then re-installing gemini to include this version of geneimpacts might be best.

**Comment by oleraj** [comment]
@brentp 
Do we need to bump the version for users to be able to point to the latest version?

**Pull request merged**
